name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy to main
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy built site to main
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Move to temp folder to preserve .git
          mkdir temp-deploy
          cp -r dist/* temp-deploy/
          
          # Clear working directory except .git
          find . -not -path "./.git*" -not -name "." -exec rm -rf {} +
          
          # Move built files to root
          cp -r temp-deploy/* ./
          rm -rf temp-deploy
          
          # Commit and push
          git add .
          git commit -m "Deploy built site to main" || echo "Nothing to commit"
          git push origin main
